config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/top' => 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト  
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end

    # book = Book.new(book_params)
    # book.save
    # redirect_to book_path(book.id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    # book.update(book_params)
    # redirect_to book_path(book.id)  
    if @book.update(book_params)
      flash[:notice] = "Book was successfully created."
      # book.update(book_params)
      redirect_to book_path(@book.id)
    else
      # @books = Book.all
      render :edit
    end


   
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

  <div class="field">
    <h4>Title</h4>
    <%= f.text_field :title %>
  </div>

  <div class="field">  
    <h4>Body</h4>
    <%= f.text_area :body %>
  </div>
  
  <div class="field">
    <%= f.submit 'Update Book' %>
  </div>

  <%= link_to "Show", book_path(@book.id) %>
  <span>|</span>
  <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<body>
<h1>Books</h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>
  <% @books.each do |book| %>
  <tbody>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book.id) %></td>
      <!-- なんかこの下は@無くすと画面遷移されるようになる -->
      <td><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
    </tr>
  </tbody>
<% end %>
</table>

<h2>New book</h2>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!-- form_with部分 -->
<%= form_with model: @book do |f| %>
  <div class="field">
    <h4>Title</h4>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <h4>Body</h4>
    <%= f.text_area :body %><br>
  </div>
    <%= f.submit 'Create Book' %>
<% end %>

</body>

app/views/books/show.html.erb
<body>
  <div>
    <%= flash[:notice] %>
  </div>
  <p>
    <span class="show_span">Title:</span><%= @book.title %>
  </p>
  <p>
    <span class="show_span">Body:</span><%= @book.body %>
  </p>

  <%= link_to "Edit", edit_book_path(@book.id) %>
  <span>|</span>
  <%= link_to "Back", books_path %>
</body>

app/views/homes/top.html.erb
<body>
<h1>ようこそ <span class="top_span">Bookers</span> へ！</h1>
<p><span class="top_span">Bookers</span> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%= link_to "start", books_path %></p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>